import Link from "next/link"
import "./globals.css"

export const metadata = {
	title: "Dispute AI",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`flex h-screen overflow-y-hidden bg-[#14141f] `}>{children}</body>
		</html>
	)
}
