
import { account } from "@/appwrite"
import Link from "next/link"
import { LogoutButton } from "@/components/LogoutButton"

export const metadata = {
	title: "Dispute AI",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

	return (
		<html lang="en">
			<body className={`flex h-screen overflow-y-hidden bg-[#14161f] `}>
				{/* sidebar */}
				<div className="flex h-screen w-20 flex-col items-center gap-10 border-r border-r-white/10 bg-white/10 py-3 text-white">
					<a href="/" className="rounded-full bg-transparent p-3 transition-colors duration-300 ease-in-out hover:bg-white/20 hover:p-3">
						<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
							<path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
						</svg>
					</a>

					<div className="flex flex-col items-center gap-3">
						<a href="/dashboard" className="group flex flex-col items-center gap-1 rounded-full p-2 text-[10px] font-medium">
							<div className="rounded-full py-[3px] transition-all duration-300 ease-in-out group-hover:bg-white/10 group-hover:px-3 group-hover:py-[3px]">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
									<path strokeLinecap="round" strokeLinejoin="round" d="M2.25 7.125C2.25 6.504 2.754 6 3.375 6h6c.621 0 1.125.504 1.125 1.125v3.75c0 .621-.504 1.125-1.125 1.125h-6a1.125 1.125 0 01-1.125-1.125v-3.75zM14.25 8.625c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v8.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-8.25zM3.75 16.125c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v2.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-2.25z" />
								</svg>
							</div>
							<p className="relative -top-[2px]">Dashboard</p>
						</a>
						<Link href="dashboard/clients" className="group flex flex-col items-center gap-1 rounded-full p-2 text-[10px] font-medium">
							<div className="rounded-full py-[3px] transition-all duration-300 ease-in-out group-hover:bg-white/10 group-hover:px-3 group-hover:py-[3px]">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
									<path strokeLinecap="round" strokeLinejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
								</svg>
							</div>
							<p className="relative -top-[2px]">Clients</p>
						</Link>
						<a href="/" className="group flex flex-col items-center gap-1 rounded-full p-2 text-[10px] font-medium">
							<div className="rounded-full py-[3px] transition-all duration-300 ease-in-out group-hover:bg-white/10 group-hover:px-3 group-hover:py-[3px]">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
									<path strokeLinecap="round" strokeLinejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
								</svg>
							</div>

							<p className="relative -top-[2px]">Contact Us</p>
						</a>
						<a href="/" className="group flex flex-col items-center gap-1 rounded-full p-2 text-[10px] font-medium">
							<div className="rounded-full py-[3px] transition-all duration-300 ease-in-out group-hover:bg-white/10 group-hover:px-3 group-hover:py-[3px]">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
									<path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75M15 10.5a3 3 0 11-6 0 3 3 0 016 0zm3 0h.008v.008H18V10.5zm-12 0h.008v.008H6V10.5z" />
								</svg>
							</div>
							<p className="relative -top-[2px]">Subscription</p>
						</a>
					</div>
				</div>

				{/* body */}
				<div className="flex flex-1 flex-col overflow-y-auto p-5 pt-0">
					{/* top bar */}
					<div className="flex h-20 w-full items-center gap-4 ">
						<div className="flex h-[55%] w-auto items-center text-white">
							<p className="text-3xl font-black tracking-wide">Dispute</p>
							<p className="font-xs text-3xl font-light">Ai</p>
						</div>
						<div className="flex flex-1 justify-center">
							<div className="flex h-10 w-[55%] items-center gap-3 rounded-full bg-white/10 px-5 text-white">
								<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
									<path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
								</svg>
								<form>
									<input type="text" className="w-full flex-1 rounded-full bg-transparent pl-1 outline-none placeholder:text-white" placeholder="Search for client..." />
									<button type="submit" hidden>
										search
									</button>
								</form>
							</div>
						</div>
						<div className="flex  justify-end gap-4">
							<div className="flex h-10 w-10 cursor-pointer items-center justify-center text-white">
								<a href="/" className="rounded-full bg-transparent p-3 transition-colors duration-300 ease-in-out hover:bg-white/5 hover:p-3">
									<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-6 w-6">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z"
										/>
										<path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
									</svg>
								</a>
							</div>
							<div className="flex h-10 w-10 cursor-pointer items-center justify-center rounded-full bg-yellow-500 text-white">A</div>
							<LogoutButton />
						</div>
					</div>

					{/* body content */}
					<div className="flex flex-1 flex-col overflow-y-auto rounded-xl border border-white/10 bg-white/5 p-5 pt-0 ">{children}</div>
				</div>
			</body>
		</html>
	)
}
